//Book

export const RECEIVE_ALL_BOOKS = 'RECEIVE_ALL_BOOKS';
export const REQUEST_ALL_BOOKS = 'REQUEST_ALL_BOOKS';
export const ERROR_RECEIVE_ALL_BOOKS = 'ERROR_RECEIVE_ALL_BOOKS';

export const SUCCESS_DELETE_BOOK = 'SUCCESS_DELETE_BOOK';
export const ERROR_DELETE_BOOK = 'ERROR_DELETE_BOOK';
export const REQUEST_DELETE_BOOK = 'REQUEST_DELETE_BOOK';

