//Book

export const RECEIVE_BOOK = 'RECEIVE_BOOK';
export const ERROR_GET_BOOK = 'ERROR_GET_BOOK';
export const REQUEST_BOOK = 'REQUEST_BOOK';

export const REQUEST_ADD_BOOK = 'REQUEST_ADD_BOOK';
export const SUCCESS_ADD_BOOK = 'SUCCESS_ADD_BOOK';
export const ERROR_ADD_BOOK = 'ERROR_ADD_BOOK';

export const REQUEST_UPDATE_BOOK = 'REQUEST_UPDATE_BOOK';
export const SUCCESS_UPDATE_BOOK = 'SUCCESS_UPDATE_BOOK';
export const ERROR_UPDATE_BOOK = 'ERROR_UPDATE_BOOK';